"use client";
import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase";
import { ArrowLeft, UserPlus, Users } from "lucide-react";
type P={id:string;full_name:string;email:string;classification:string|null;major:string|null;status:string};
export default function RosterManagement(){
 const router=useRouter();const[rows,setRows]=useState<P[]>([]);const[name,setName]=useState("");const[email,setEmail]=useState("");const[msg,setMsg]=useState("");
 async function load(){const s=createClient();if(!s)return;const{data:a}=await s.rpc("is_admin");if(!a){router.replace("/dashboard");return}const{data}=await s.from("profiles").select("id,full_name,email,classification,major,status").order("full_name");setRows((data||[]) as P[])}
 useEffect(()=>{load()},[]);
 async function add(e:FormEvent){e.preventDefault();const s=createClient();if(!s)return;const{error}=await s.rpc("add_authorized_brother",{p_email:email.toLowerCase(),p_full_name:name});if(error){setMsg(error.message);return}setMsg("Brother authorized. He can now activate his account.");setName("");setEmail("")}
 return <main className="adminPage"><button className="backBtn" onClick={()=>router.push("/dashboard")}><ArrowLeft/> Dashboard</button><div className="pageTitleRow"><div><p className="eyebrow">E-BOARD</p><h1>Roster Management</h1><p className="pageLead">{rows.filter(x=>x.status==="active").length} activated brothers</p></div></div><div className="twoCol"><form className="formCard" onSubmit={add}><h2><UserPlus/> Authorize Brother</h2><p>Add his NSU email before he activates an account.</p><label>Full name<input required value={name} onChange={e=>setName(e.target.value)} placeholder="First Last"/></label><label>NSU email<input type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="brother@spartans.nsu.edu"/></label><button className="primarySmall">Add to Authorized Roster</button>{msg&&<p className="formMsg">{msg}</p>}</form><div className="tableCard"><div className="tableHead"><Users/> Activated Accounts</div>{rows.map(x=><div className="rosterRow" key={x.id}><div className="miniAvatar">{x.full_name.split(" ").map(n=>n[0]).join("").slice(0,2)}</div><div><b>{x.full_name}</b><span>{x.email}</span></div><div><b>{x.classification||"—"}</b><span>{x.major||"Profile incomplete"}</span></div><span className={"statusPill "+x.status}>{x.status}</span></div>)}</div></div></main>
}