"use client";
import{FormEvent,useEffect,useState}from"react";import{useRouter}from"next/navigation";import{createClient}from"@/lib/supabase";import{ArrowLeft,Trophy}from"lucide-react";
type Tx={id:string;points:number;category:string;description:string|null;status:string;created_at:string};type Rule={category:string;points:number};
export default function Points(){const r=useRouter();const[rows,setRows]=useState<Tx[]>([]);const[category,setCategory]=useState("");const[rules,setRules]=useState<Rule[]>([]);const[description,setDescription]=useState("");const[msg,setMsg]=useState("");const[org,setOrg]=useState("");const[date,setDate]=useState("");const[hours,setHours]=useState("");const[busy,setBusy]=useState(false);
const isService=/service/i.test(category);
async function load(){const s=createClient();if(!s)return;const{data:{user}}=await s.auth.getUser();if(!user){r.replace("/login");return}const{data:sem}=await s.from("semesters").select("id").eq("is_active",true).single();if(!sem)return;const[{data},{data:ruleData}]=await Promise.all([s.from("point_transactions").select("id,points,category,description,status,created_at").eq("semester_id",sem.id).order("created_at",{ascending:false}),s.from("point_rules").select("category,points").eq("semester_id",sem.id).gt("points",0).order("points",{ascending:false})]);setRows((data||[]) as Tx[]);const rr=(ruleData||[]) as Rule[];setRules(rr);if(rr.length&&!rr.some(x=>x.category===category))setCategory(rr[0].category)}
useEffect(()=>{load()},[]);
async function submit(e:FormEvent){e.preventDefault();setMsg("");setBusy(true);const s=createClient();if(!s){setBusy(false);return}const{data:{user}}=await s.auth.getUser();const{data:sem}=await s.from("semesters").select("id").eq("is_active",true).single();if(!user||!sem){setBusy(false);return}const points=rules.find(x=>x.category===category)?.points||0;let evidence_path:string|null=null;
if(isService&&(!org||!date||Number(hours)<=0)){setMsg("Organization, date and hours are required for outside service.");setBusy(false);return}
const{error}=await s.from("point_transactions").insert({profile_id:user.id,semester_id:sem.id,points,kind:"credit",category,description,created_by:user.id,status:"pending",service_organization:isService?org:null,service_date:isService?date:null,service_hours:isService?Number(hours):null,evidence_path});
if(error){if(evidence_path)await s.storage.from("point-evidence").remove([evidence_path]);setMsg(error.message);setBusy(false);return}setMsg("Submitted for E-Board review.");setDescription("");setOrg("");setDate("");setHours("");setBusy(false);load()}
const total=rows.filter(x=>x.status==="approved").reduce((n,x)=>n+x.points,0);
return <main className="adminPage"><button className="backBtn" onClick={()=>r.push("/dashboard")}><ArrowLeft/> Dashboard</button><p className="eyebrow">MY ACTIVITY</p><h1>Points</h1><p className="pageLead"><b>{total}</b> approved points this semester. Outside service can be submitted here. Chapter service hours come automatically from QR attendance and cannot be manually duplicated.</p><div className="twoCol"><form className="formCard" onSubmit={submit}><h2><Trophy/> Submit Activity</h2><label>How did you earn points?<select required value={category} onChange={e=>setCategory(e.target.value)}>{rules.map(x=><option key={x.category} value={x.category}>{x.category} (+{x.points})</option>)}</select></label>{isService&&<><div className="serviceNote"><b>Outside service only</b><span>For chapter service events, use the event QR check-in/out. Those hours are recorded automatically.</span></div><label>Service organization<input required value={org} onChange={e=>setOrg(e.target.value)}/></label><label>Service date<input type="date" required value={date} onChange={e=>setDate(e.target.value)}/></label><label>Service hours<input type="number" min=".25" max="24" step=".25" required value={hours} onChange={e=>setHours(e.target.value)}/></label></>}<label>Description<textarea required value={description} onChange={e=>setDescription(e.target.value)} placeholder={isService?"What service did you perform?":"What did you do?"}/></label><button disabled={busy} className="primarySmall">{busy?"Submitting…":"Submit for Review"}</button>{msg&&<p className="formMsg">{msg}</p>}</form><div className="tableCard"><h2>My Requests</h2>{rows.length===0?<p>No point activity yet.</p>:rows.map(x=><div className="simpleRow" key={x.id}><div><b>{x.category}</b><span>{x.description}</span></div><strong>{x.points>0?"+":""}{x.points}</strong><span className={"statusPill "+x.status}>{x.status}</span></div>)}</div></div></main>}